theme = "monokai_pro_machine"

[editor]
true-color = true
bufferline = "always"
line-number = "relative"
rulers = [140]
auto-completion=true
auto-save=true
auto-format=true
scroll-lines = 1
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
mouse = true
text-width = 135

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
max-wrap = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "register", "position", "file-encoding"]
separator = "│"


[editor.lsp]
enable= true
auto-signature-help= true
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true
goto-reference-include-declaration = true
snippets = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # deselect all; keep primary cursor only
tab = "goto_next_function" # select and jump to the next function via Treesitter
S-tab = "goto_prev_function" # select and jump to the previous function via Treesitter c
backspace = ["delete_char_backward"] # counterpart for `d`
p = "paste_before" # switched with P
P = "paste_after" # switched with p
O = ["open_above", "normal_mode"] # do not leave normal mode
o = ["open_below", "normal_mode"] # do not leave normal mode
C-s = ":w" # save
C-v = "paste_clipboard_before" # paste from clipboard
C-c = "yank_to_clipboard" # copy to clipboard
space.p = "paste_clipboard_before" # switched with P
space.P = "paste_clipboard_after" # switched with p
C-k = "toggle_comments"
C-q = ":q"
d = "delete_selection_noyank"
A-d = "delete_selection"
C-j = "save_selection"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"] # go to the simplest scenario!

[keys.insert]
C-c = "yank_to_clipboard" # copy to clipboard
C-v = ["paste_clipboard_before"]
C-d=["save_selection", "extend_to_line_bounds", "toggle_comments", "yank", "paste_before", "jump_backward","toggle_comments" ]
C-left = ["move_prev_word_start"] # jump and select word left
C-right = ["move_next_word_end"] # jump and select word right
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"] # moves line up; like vscode
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"] # move line down; like vscode
C-s = ":w" # save
