[language-server.jdtls]
command = "jdtls"
args = ["-data", "/home/dosynk/.cache/jdtls/workspace"]

[[language]]
name = "java"
scope = "source.java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ".git"]
language-servers = ["jdtls"]  

[[language]]
name = "slang"
scope = "source.lang"
injection-regex = "slang"
file-types = ["slang"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "slangd" ]
indent = { tab-width = 4, unit = "  " }

[[grammar]]
name = "slang"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-slang", rev = "327b1b821c255867a4fb724c8eee48887e3d014b" }

